apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-secrets
  namespace: myapp-dev
spec:
  provider: azure
  parameters:
    keyvaultName: "mykube-dev"
    objects: |
      array:
        - objectName: mongo-password
          objectType: secret
    tenantId: "ec73c9e5-b6b6-45a6-962d-822e86cdc0fa"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-test
  namespace: myapp-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-test
  template:
    metadata:
      labels:
        app: secret-test
    spec:
      containers:
      - name: alpine
        image: alpine:3.18
        command: ["/bin/sh", "-c", "sleep 3600"]   # keep pod alive
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "myapp-secrets"
